package org.nescent.mmdb.hibernate.dao;

import java.util.HashSet;
import java.util.Set;


/**
 * MmCvTerm generated by MyEclipse - Hibernate Tools
 */

public class MmCvTerm  implements java.io.Serializable {


    // Fields    

     private Integer cvtermOid;
     private String namespace;
     private String name;
     private String description;
     private String synonymName;
     private String valueType;
     private String isValueComputed;
     private Set mmPermissions = new HashSet(0);
     private Set mmTermRelationshipsForCvtermObjectOid = new HashSet(0);
     private Set mmExperimentStudies = new HashSet(0);
     private Set mmExperimentValues = new HashSet(0);
     private Set mmTermRelationshipsForCvtermPredicateOid = new HashSet(0);
     private Set mmPopSampleAttrCvtermAssocs = new HashSet(0);
     private Set mmExperimentStudyAttrCvtermAssocs = new HashSet(0);
     private Set mmTermRelationshipsForCvtermSubjectOid = new HashSet(0);
     private Set mmDataRecords = new HashSet(0);
     private Set mmSpeciesAttrCvtermAssocs = new HashSet(0);


    // Constructors

    /** default constructor */
    public MmCvTerm() {
    }

	/** minimal constructor */
    public MmCvTerm(Integer cvtermOid, String namespace, String name) {
        this.cvtermOid = cvtermOid;
        this.namespace = namespace;
        this.name = name;
    }
    
    /** full constructor */
    public MmCvTerm(Integer cvtermOid, String namespace, String name, String description, String synonymName, String valueType, String isValueComputed, Set mmPermissions, Set mmTermRelationshipsForCvtermObjectOid, Set mmExperimentStudies, Set mmExperimentValues, Set mmTermRelationshipsForCvtermPredicateOid, Set mmPopSampleAttrCvtermAssocs, Set mmExperimentStudyAttrCvtermAssocs, Set mmTermRelationshipsForCvtermSubjectOid, Set mmDataRecords, Set mmSpeciesAttrCvtermAssocs) {
        this.cvtermOid = cvtermOid;
        this.namespace = namespace;
        this.name = name;
        this.description = description;
        this.synonymName = synonymName;
        this.valueType = valueType;
        this.isValueComputed = isValueComputed;
        this.mmPermissions = mmPermissions;
        this.mmTermRelationshipsForCvtermObjectOid = mmTermRelationshipsForCvtermObjectOid;
        this.mmExperimentStudies = mmExperimentStudies;
        this.mmExperimentValues = mmExperimentValues;
        this.mmTermRelationshipsForCvtermPredicateOid = mmTermRelationshipsForCvtermPredicateOid;
        this.mmPopSampleAttrCvtermAssocs = mmPopSampleAttrCvtermAssocs;
        this.mmExperimentStudyAttrCvtermAssocs = mmExperimentStudyAttrCvtermAssocs;
        this.mmTermRelationshipsForCvtermSubjectOid = mmTermRelationshipsForCvtermSubjectOid;
        this.mmDataRecords = mmDataRecords;
        this.mmSpeciesAttrCvtermAssocs = mmSpeciesAttrCvtermAssocs;
    }

   
    // Property accessors

    public Integer getCvtermOid() {
        return this.cvtermOid;
    }
    
    public void setCvtermOid(Integer cvtermOid) {
        this.cvtermOid = cvtermOid;
    }

    public String getNamespace() {
        return this.namespace;
    }
    
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getSynonymName() {
        return this.synonymName;
    }
    
    public void setSynonymName(String synonymName) {
        this.synonymName = synonymName;
    }

    public String getValueType() {
        return this.valueType;
    }
    
    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    public String getIsValueComputed() {
        return this.isValueComputed;
    }
    
    public void setIsValueComputed(String isValueComputed) {
        this.isValueComputed = isValueComputed;
    }

    public Set getMmPermissions() {
        return this.mmPermissions;
    }
    
    public void setMmPermissions(Set mmPermissions) {
        this.mmPermissions = mmPermissions;
    }

    public Set getMmTermRelationshipsForCvtermObjectOid() {
        return this.mmTermRelationshipsForCvtermObjectOid;
    }
    
    public void setMmTermRelationshipsForCvtermObjectOid(Set mmTermRelationshipsForCvtermObjectOid) {
        this.mmTermRelationshipsForCvtermObjectOid = mmTermRelationshipsForCvtermObjectOid;
    }

    public Set getMmExperimentStudies() {
        return this.mmExperimentStudies;
    }
    
    public void setMmExperimentStudies(Set mmExperimentStudies) {
        this.mmExperimentStudies = mmExperimentStudies;
    }

    public Set getMmExperimentValues() {
        return this.mmExperimentValues;
    }
    
    public void setMmExperimentValues(Set mmExperimentValues) {
        this.mmExperimentValues = mmExperimentValues;
    }

    public Set getMmTermRelationshipsForCvtermPredicateOid() {
        return this.mmTermRelationshipsForCvtermPredicateOid;
    }
    
    public void setMmTermRelationshipsForCvtermPredicateOid(Set mmTermRelationshipsForCvtermPredicateOid) {
        this.mmTermRelationshipsForCvtermPredicateOid = mmTermRelationshipsForCvtermPredicateOid;
    }

    public Set getMmPopSampleAttrCvtermAssocs() {
        return this.mmPopSampleAttrCvtermAssocs;
    }
    
    public void setMmPopSampleAttrCvtermAssocs(Set mmPopSampleAttrCvtermAssocs) {
        this.mmPopSampleAttrCvtermAssocs = mmPopSampleAttrCvtermAssocs;
    }

    public Set getMmExperimentStudyAttrCvtermAssocs() {
        return this.mmExperimentStudyAttrCvtermAssocs;
    }
    
    public void setMmExperimentStudyAttrCvtermAssocs(Set mmExperimentStudyAttrCvtermAssocs) {
        this.mmExperimentStudyAttrCvtermAssocs = mmExperimentStudyAttrCvtermAssocs;
    }

    public Set getMmTermRelationshipsForCvtermSubjectOid() {
        return this.mmTermRelationshipsForCvtermSubjectOid;
    }
    
    public void setMmTermRelationshipsForCvtermSubjectOid(Set mmTermRelationshipsForCvtermSubjectOid) {
        this.mmTermRelationshipsForCvtermSubjectOid = mmTermRelationshipsForCvtermSubjectOid;
    }

    public Set getMmDataRecords() {
        return this.mmDataRecords;
    }
    
    public void setMmDataRecords(Set mmDataRecords) {
        this.mmDataRecords = mmDataRecords;
    }

    public Set getMmSpeciesAttrCvtermAssocs() {
        return this.mmSpeciesAttrCvtermAssocs;
    }
    
    public void setMmSpeciesAttrCvtermAssocs(Set mmSpeciesAttrCvtermAssocs) {
        this.mmSpeciesAttrCvtermAssocs = mmSpeciesAttrCvtermAssocs;
    }
   








}