package org.nescent.mmdb.hibernate.dao;

/**
 * MmDataRecord generated by MyEclipse - Hibernate Tools
 */

public class MmDataRecord implements java.io.Serializable,
	Comparable<MmDataRecord> {

    // Fields

    private Integer dataRecordOid;
    private MmCvTerm mmCvTerm;
    private MmExperimentStudy mmExperimentStudy;
    private String name;
    private String type;
    private Double outCrossingValue;
    private Double selfingValue;
    private Double outCrossingStdDev;
    private Double selfingStdDev;

    // Constructors

    /** default constructor */
    public MmDataRecord() {
    }

    /** minimal constructor */
    public MmDataRecord(Integer dataRecordOid) {
	this.dataRecordOid = dataRecordOid;
    }

    /** full constructor */
    public MmDataRecord(Integer dataRecordOid, MmCvTerm mmCvTerm,
	    MmExperimentStudy mmExperimentStudy, String name, String type,
	    Double outCrossingValue, Double selfingValue,
	    Double outCrossingStdDev, Double selfingStdDev) {
	this.dataRecordOid = dataRecordOid;
	this.mmCvTerm = mmCvTerm;
	this.mmExperimentStudy = mmExperimentStudy;
	this.name = name;
	this.type = type;
	this.outCrossingValue = outCrossingValue;
	this.selfingValue = selfingValue;
	this.outCrossingStdDev = outCrossingStdDev;
	this.selfingStdDev = selfingStdDev;
    }

    // Property accessors

    public Integer getDataRecordOid() {
	return this.dataRecordOid;
    }

    public void setDataRecordOid(Integer dataRecordOid) {
	this.dataRecordOid = dataRecordOid;
    }

    public MmCvTerm getMmCvTerm() {
	return this.mmCvTerm;
    }

    public void setMmCvTerm(MmCvTerm mmCvTerm) {
	this.mmCvTerm = mmCvTerm;
    }

    public MmExperimentStudy getMmExperimentStudy() {
	return this.mmExperimentStudy;
    }

    public void setMmExperimentStudy(MmExperimentStudy mmExperimentStudy) {
	this.mmExperimentStudy = mmExperimentStudy;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getType() {
	return this.type;
    }

    public void setType(String type) {
	this.type = type;
    }

    public Double getOutCrossingValue() {
	return this.outCrossingValue;
    }

    public void setOutCrossingValue(Double outCrossingValue) {
	this.outCrossingValue = outCrossingValue;
    }

    public Double getSelfingValue() {
	return this.selfingValue;
    }

    public void setSelfingValue(Double selfingValue) {
	this.selfingValue = selfingValue;
    }

    public Double getOutCrossingStdDev() {
	return this.outCrossingStdDev;
    }

    public void setOutCrossingStdDev(Double outCrossingStdDev) {
	this.outCrossingStdDev = outCrossingStdDev;
    }

    public Double getSelfingStdDev() {
	return this.selfingStdDev;
    }

    public void setSelfingStdDev(Double selfingStdDev) {
	this.selfingStdDev = selfingStdDev;
    }

    public int compareTo(MmDataRecord assoc) {
	MmCvTerm term = assoc.getMmCvTerm();
	int r = this.getMmCvTerm().getName().compareTo(term.getName());
	if (r == 0) {
	    return this.getDataRecordOid().compareTo(assoc.getDataRecordOid());
	}
	return r;
    }

}