package org.nescent.mmdb.hibernate.dao;

/**
 * MmExperimentStudyAttrCvtermAssoc generated by MyEclipse - Hibernate Tools
 */

public class MmExperimentStudyAttrCvtermAssoc implements java.io.Serializable,
	Comparable<MmExperimentStudyAttrCvtermAssoc> {

    // Fields

    private Integer mmexpOid;
    private MmCvTerm mmCvTerm;
    private MmExperimentStudy mmExperimentStudy;
    private String value;

    // Constructors

    /** default constructor */
    public MmExperimentStudyAttrCvtermAssoc() {
    }

    /** minimal constructor */
    public MmExperimentStudyAttrCvtermAssoc(Integer mmexpOid, String value) {
	this.mmexpOid = mmexpOid;
	this.value = value;
    }

    /** full constructor */
    public MmExperimentStudyAttrCvtermAssoc(Integer mmexpOid,
	    MmCvTerm mmCvTerm, MmExperimentStudy mmExperimentStudy, String value) {
	this.mmexpOid = mmexpOid;
	this.mmCvTerm = mmCvTerm;
	this.mmExperimentStudy = mmExperimentStudy;
	this.value = value;
    }

    // Property accessors

    public int compareTo(MmExperimentStudyAttrCvtermAssoc assoc) {
	MmCvTerm term = assoc.getMmCvTerm();
	int r = this.getMmCvTerm().getName().compareTo(term.getName());
	if (r == 0) {
	    return this.getMmexpOid().compareTo(assoc.getMmexpOid());
	}
	return r;
    }

    public Integer getMmexpOid() {
	return this.mmexpOid;
    }

    public void setMmexpOid(Integer mmexpOid) {
	this.mmexpOid = mmexpOid;
    }

    public MmCvTerm getMmCvTerm() {
	return this.mmCvTerm;
    }

    public void setMmCvTerm(MmCvTerm mmCvTerm) {
	this.mmCvTerm = mmCvTerm;
    }

    public MmExperimentStudy getMmExperimentStudy() {
	return this.mmExperimentStudy;
    }

    public void setMmExperimentStudy(MmExperimentStudy mmExperimentStudy) {
	this.mmExperimentStudy = mmExperimentStudy;
    }

    public String getValue() {
	return this.value;
    }

    public void setValue(String value) {
	this.value = value;
    }

}