package org.nescent.mmdb.hibernate.dao;

import java.util.HashSet;
import java.util.Set;


/**
 * MmMatingSystemStudy generated by MyEclipse - Hibernate Tools
 */

public class MmMatingSystemStudy  implements java.io.Serializable {


    // Fields    

     private Integer matingSystemStudyOid;
     private MmReferencePart mmReferencePart;
     private MmSpecies mmSpecies;
     private String latitude;
     private Set mmSpeciesAttrCvtermAssocs = new HashSet(0);


    // Constructors

    /** default constructor */
    public MmMatingSystemStudy() {
    }

    
    /** full constructor */
    public MmMatingSystemStudy(MmReferencePart mmReferencePart, MmSpecies mmSpecies, String latitude, Set mmSpeciesAttrCvtermAssocs) {
        this.mmReferencePart = mmReferencePart;
        this.mmSpecies = mmSpecies;
        this.latitude = latitude;
        this.mmSpeciesAttrCvtermAssocs = mmSpeciesAttrCvtermAssocs;
    }

   
    // Property accessors

    public Integer getMatingSystemStudyOid() {
        return this.matingSystemStudyOid;
    }
    
    public void setMatingSystemStudyOid(Integer matingSystemStudyOid) {
        this.matingSystemStudyOid = matingSystemStudyOid;
    }

    public MmReferencePart getMmReferencePart() {
        return this.mmReferencePart;
    }
    
    public void setMmReferencePart(MmReferencePart mmReferencePart) {
        this.mmReferencePart = mmReferencePart;
    }

    public MmSpecies getMmSpecies() {
        return this.mmSpecies;
    }
    
    public void setMmSpecies(MmSpecies mmSpecies) {
        this.mmSpecies = mmSpecies;
    }

    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public Set getMmSpeciesAttrCvtermAssocs() {
        return this.mmSpeciesAttrCvtermAssocs;
    }
    
    public void setMmSpeciesAttrCvtermAssocs(Set mmSpeciesAttrCvtermAssocs) {
        this.mmSpeciesAttrCvtermAssocs = mmSpeciesAttrCvtermAssocs;
    }
   








}