package org.nescent.mmdb.hibernate.dao;



/**
 * MmPermission generated by MyEclipse - Hibernate Tools
 */

public class MmPermission  implements java.io.Serializable {


    // Fields    

     private Integer permissionOid;
     private MmRole mmRole;
     private MmCvTerm mmCvTerm;
     private String access;
     private String scope;


    // Constructors

    /** default constructor */
    public MmPermission() {
    }

	/** minimal constructor */
    public MmPermission(Integer permissionOid, MmCvTerm mmCvTerm, String access, String scope) {
        this.permissionOid = permissionOid;
        this.mmCvTerm = mmCvTerm;
        this.access = access;
        this.scope = scope;
    }
    
    /** full constructor */
    public MmPermission(Integer permissionOid, MmRole mmRole, MmCvTerm mmCvTerm, String access, String scope) {
        this.permissionOid = permissionOid;
        this.mmRole = mmRole;
        this.mmCvTerm = mmCvTerm;
        this.access = access;
        this.scope = scope;
    }

   
    // Property accessors

    public Integer getPermissionOid() {
        return this.permissionOid;
    }
    
    public void setPermissionOid(Integer permissionOid) {
        this.permissionOid = permissionOid;
    }

    public MmRole getMmRole() {
        return this.mmRole;
    }
    
    public void setMmRole(MmRole mmRole) {
        this.mmRole = mmRole;
    }

    public MmCvTerm getMmCvTerm() {
        return this.mmCvTerm;
    }
    
    public void setMmCvTerm(MmCvTerm mmCvTerm) {
        this.mmCvTerm = mmCvTerm;
    }

    public String getAccess() {
        return this.access;
    }
    
    public void setAccess(String access) {
        this.access = access;
    }

    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }
   








}