package org.nescent.mmdb.hibernate.dao;



/**
 * MmPopSampleAttrCvtermAssoc generated by MyEclipse - Hibernate Tools
 */

public class MmPopSampleAttrCvtermAssoc  implements java.io.Serializable {


    // Fields    

     private Integer mpsacaOid;
     private MmCvTerm mmCvTerm;
     private MmPopulationSample mmPopulationSample;
     private String value;


    // Constructors

    /** default constructor */
    public MmPopSampleAttrCvtermAssoc() {
    }

	/** minimal constructor */
    public MmPopSampleAttrCvtermAssoc(String value) {
        this.value = value;
    }
    
    /** full constructor */
    public MmPopSampleAttrCvtermAssoc(MmCvTerm mmCvTerm, MmPopulationSample mmPopulationSample, String value) {
        this.mmCvTerm = mmCvTerm;
        this.mmPopulationSample = mmPopulationSample;
        this.value = value;
    }

   
    // Property accessors

    public Integer getMpsacaOid() {
        return this.mpsacaOid;
    }
    
    public void setMpsacaOid(Integer mpsacaOid) {
        this.mpsacaOid = mpsacaOid;
    }

    public MmCvTerm getMmCvTerm() {
        return this.mmCvTerm;
    }
    
    public void setMmCvTerm(MmCvTerm mmCvTerm) {
        this.mmCvTerm = mmCvTerm;
    }

    public MmPopulationSample getMmPopulationSample() {
        return this.mmPopulationSample;
    }
    
    public void setMmPopulationSample(MmPopulationSample mmPopulationSample) {
        this.mmPopulationSample = mmPopulationSample;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
   








}