package org.nescent.mmdb.hibernate.dao;

import java.util.HashSet;
import java.util.Set;


/**
 * MmReference generated by MyEclipse - Hibernate Tools
 */

public class MmReference  implements java.io.Serializable {


    // Fields    

     private Integer referenceOid;
     private String citation;
     private String fullReference;
     private Set mmReferenceParts = new HashSet(0);


    // Constructors

    /** default constructor */
    public MmReference() {
    }

    
    /** full constructor */
    public MmReference(String citation, String fullReference, Set mmReferenceParts) {
        this.citation = citation;
        this.fullReference = fullReference;
        this.mmReferenceParts = mmReferenceParts;
    }

   
    // Property accessors

    public Integer getReferenceOid() {
        return this.referenceOid;
    }
    
    public void setReferenceOid(Integer referenceOid) {
        this.referenceOid = referenceOid;
    }

    public String getCitation() {
        return this.citation;
    }
    
    public void setCitation(String citation) {
        this.citation = citation;
    }

    public String getFullReference() {
        return this.fullReference;
    }
    
    public void setFullReference(String fullReference) {
        this.fullReference = fullReference;
    }

    public Set getMmReferenceParts() {
        return this.mmReferenceParts;
    }
    
    public void setMmReferenceParts(Set mmReferenceParts) {
        this.mmReferenceParts = mmReferenceParts;
    }
   








}