package org.nescent.mmdb.hibernate.dao;

import java.util.HashSet;
import java.util.Set;


/**
 * MmSpecies generated by MyEclipse - Hibernate Tools
 */

public class MmSpecies  implements java.io.Serializable {


    // Fields    

     private Integer speciesOid;
     private String family;
     private String genus;
     private String species;
     private Set mmPopulationSamples = new HashSet(0);
     private Set mmMatingSystemStudies = new HashSet(0);


    // Constructors

    /** default constructor */
    public MmSpecies() {
    }

	/** minimal constructor */
    public MmSpecies(Integer speciesOid, String genus, String species) {
        this.speciesOid = speciesOid;
        this.genus = genus;
        this.species = species;
    }
    
    /** full constructor */
    public MmSpecies(Integer speciesOid, String family, String genus, String species, Set mmPopulationSamples, Set mmMatingSystemStudies) {
        this.speciesOid = speciesOid;
        this.family = family;
        this.genus = genus;
        this.species = species;
        this.mmPopulationSamples = mmPopulationSamples;
        this.mmMatingSystemStudies = mmMatingSystemStudies;
    }

   
    // Property accessors

    public Integer getSpeciesOid() {
        return this.speciesOid;
    }
    
    public void setSpeciesOid(Integer speciesOid) {
        this.speciesOid = speciesOid;
    }

    public String getFamily() {
        return this.family;
    }
    
    public void setFamily(String family) {
        this.family = family;
    }

    public String getGenus() {
        return this.genus;
    }
    
    public void setGenus(String genus) {
        this.genus = genus;
    }

    public String getSpecies() {
        return this.species;
    }
    
    public void setSpecies(String species) {
        this.species = species;
    }

    public Set getMmPopulationSamples() {
        return this.mmPopulationSamples;
    }
    
    public void setMmPopulationSamples(Set mmPopulationSamples) {
        this.mmPopulationSamples = mmPopulationSamples;
    }

    public Set getMmMatingSystemStudies() {
        return this.mmMatingSystemStudies;
    }
    
    public void setMmMatingSystemStudies(Set mmMatingSystemStudies) {
        this.mmMatingSystemStudies = mmMatingSystemStudies;
    }
   








}