package org.nescent.mmdb.hibernate.dao;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MmUserAccount generated by MyEclipse - Hibernate Tools
 */

public class MmUserAccount  implements java.io.Serializable {


    // Fields    

     private Integer userAccountOid;
     private String userName;
     private String password;
     private Date createDate;
     private String enableDisableStatus;
     private Set mmUserAcctRoleAssocs = new HashSet(0);


    // Constructors

    /** default constructor */
    public MmUserAccount() {
    }

	/** minimal constructor */
    public MmUserAccount(Integer userAccountOid, String userName, String password, String enableDisableStatus) {
        this.userAccountOid = userAccountOid;
        this.userName = userName;
        this.password = password;
        this.enableDisableStatus = enableDisableStatus;
    }
    
    /** full constructor */
    public MmUserAccount(Integer userAccountOid, String userName, String password, Date createDate, String enableDisableStatus, Set mmUserAcctRoleAssocs) {
        this.userAccountOid = userAccountOid;
        this.userName = userName;
        this.password = password;
        this.createDate = createDate;
        this.enableDisableStatus = enableDisableStatus;
        this.mmUserAcctRoleAssocs = mmUserAcctRoleAssocs;
    }

   
    // Property accessors

    public Integer getUserAccountOid() {
        return this.userAccountOid;
    }
    
    public void setUserAccountOid(Integer userAccountOid) {
        this.userAccountOid = userAccountOid;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getEnableDisableStatus() {
        return this.enableDisableStatus;
    }
    
    public void setEnableDisableStatus(String enableDisableStatus) {
        this.enableDisableStatus = enableDisableStatus;
    }

    public Set getMmUserAcctRoleAssocs() {
        return this.mmUserAcctRoleAssocs;
    }
    
    public void setMmUserAcctRoleAssocs(Set mmUserAcctRoleAssocs) {
        this.mmUserAcctRoleAssocs = mmUserAcctRoleAssocs;
    }
   








}